# name in square brackets
# screen coordinates go top-left, top-right, bottom-left, bottom-right
# text_colour in rgb values

[ben]
image = "ben.png"
screen = [ 318, 17, 724, 20, 317, 274, 721, 273 ]
widescreen = true
overlay_dark = "ben-dark-overlay.png"
overlay_light = "ben-light-overlay.png"

[dan]
image = "dan.jpg"
screen = [ 44, 22, 330, 189, 25, 404, 329, 438 ]
widescreen = false
overlay_dark = "dan-dark-overlay.png"
overlay_light = "dan-light-overlay.png"

[pete]
image = "pete.png"
screen = [ 29, -11, 488, 67, -4, 399, 485, 358 ]
widescreen = false
overlay_dark = "pete-dark-overlay.png"
overlay_light = "pete-light-overlay.png"

[ruth]
image = "ruth.png"
screen = [ 93, 74, 515, 87, 84, 312, 516, 313 ]
widescreen = true
overlay_dark = "ruth-dark-overlay.png"
overlay_light = "ruth-light-overlay.png"

[ryan]
image = "ryan.png"
screen = [ 0, 36, 338, 64, -4, 316, 338, 294 ]
widescreen = false
overlay_dark = "ryan-dark-overlay.png"
overlay_light = "ryan-light-overlay.png"

[seren]
image = "seren.png"
screen = [ 235, 11, 728, 5, 233, 355, 728, 372 ]
widescreen = false
overlay_dark = "seren-dark-overlay.png"
overlay_light = "seren-light-overlay.png"
